fuzzing:
  output_folder: ./outputs/full_run/lightftp/
  num: 2000
  total_time: 0.91
  log_level: 3
  otf: false
  resume: false
  evaluate: false
  use_hand_written_prompt: false
  no_input_prompt: false
  prompt_strategy: 0

target:
  language: ftp
  path_documentation: config/documentation/protocol/lightftp.md
  path_example_code: /home/protocols/LightFTP
  trigger_to_generate_input: "Generate valid FTP command sequences (USER, PASS, LIST, STOR) for lightFTP."
  input_hint: "USER test\r\nPASS test@\r\n"
  path_hand_written_prompt:
  target_string: "USER"

llm:
  temperature: 1
  batch_size: 30
  device: cuda
  model_name: bigcode/starcoderbase
  max_length: 1024
